### ISSUE TITLE
Fails with 'init terminating in do_boot ()' in RabbitMQ 3.6.9

### ISSUE THREAD

**Issue by leefowlercu** [rabbitmq/rabbitmq-clusterer#23]
I've searched high and low for a way to debug this but I cannot seem to get any information on what would be causing this. I'm attempting to cluster 3 RabbitMQ 3.6.9 nodes in Kubernetes using `rabbitmq-clusterer` but I am running into an issue where `rabbitmq-server` fails and prints a pretty unhelpful error message.

Setup:
I am using the `rabbitmq-clusterer` `.ez` file from here: https://www.rabbitmq.com/community-plugins/v3.6.x/rabbitmq_clusterer-3.6.x-667f92b0.ez (I have used the release on BinTray as well, same issue)
RabbitMQ Server v 3.6.9

Steps to reproduce:
Here is a simple dockerfile which highlights the issue:

```
FROM rabbitmq:3.6.9-management

ENV RABBITMQ_BOOT_MODULE=rabbitmq_clusterer \
    RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-pa /plugins/rabbitmq_clusterer-3.6.9.ez/rabbitmq_clusterer-3.6.x-667f92b0/ebin"

ADD rabbitmq_clusterer-3.6.9.ez /plugins/rabbitmq_clusterer-3.6.9.ez

RUN apt-get update \
 && apt-get install -y jq curl unzip nano \
 && rabbitmq-plugins enable --offline rabbitmq_clusterer
```

When run this produces an Erlang crash with the message: 

```
{"init terminating in do_boot",{undef,[{rabbitmq_clusterer,boot,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
```

When I modify `rabbitmq-server` to print commands as they are executed here is the offending `erl` invocation:

```
RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq ERL_MAX_ETS_TABLES=50000 exec erl -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/ebin -noinput -s rabbitmq_clusterer boot -sname rabbit@5bc2e8bf26f9 -boot start_sasl -config /etc/rabbitmq/rabbitmq +W w +A 64 +P 1048576 +t 5000000 +stbt db +zdbbl 32000 +K true -kernel inet_default_connect_options [{nodelay,true}] -pa /plugins/rabbitmq_clusterer-3.6.9.ez/rabbitmq_clusterer-3.6.x-667f92b0/ebin -sasl errlog_type error -sasl sasl_error_logger tty -rabbit error_logger tty -rabbit sasl_error_logger tty -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/lib/rabbitmq/plugins:/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/plugins" -rabbit plugins_expand_dir "/var/lib/rabbitmq/mnesia/rabbit@5bc2e8bf26f9-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@5bc2e8bf26f9" +B i -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
```

Nothing is printed to RabbitMQ logs

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
The message says that `rabbitmq_clusterer:boot/0` is undefined, which means the plugin is not on the VM code path.

**Comment by leefowlercu** [comment]
On the `erl` invocation `-pa /plugins/rabbitmq_clusterer-3.6.9.ez/rabbitmq_clusterer-3.6.x-667f92b0/ebin` is correctly set, placing that path on the VM code path.

**Comment by michaelklishin** [comment]
I'm hardly a Kubernetes expert but these lines

```
RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-pa /plugins/rabbitmq_clusterer-3.6.9.ez/rabbitmq_clusterer-3.6.x-667f92b0/ebin"
ADD rabbitmq_clusterer-3.6.9.ez /plugins/rabbitmq_clusterer-3.6.9.ez
```

and

```
-pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/ebin
```
do not use matching paths.

**Comment by michaelklishin** [comment]
@LeeFowlerCU well, the VM disagrees. This is rabbitmq-users material. The mismatching paths above is what I'd recommend investigating first.

**Comment by michaelklishin** [comment]
@LeeFowlerCU the file you are using is [from December 2015](https://www.rabbitmq.com/community-plugins/v3.6.x/). This plugin hardly changed since then but please use [the most recent version](https://bintray.com/rabbitmq/community-plugins/rabbitmq_clusterer/v1.0.3).

**Comment by leefowlercu** [comment]
That first VM code path declaration is generated by the `rabbitmq-server` script itself, I'll test combining the paths in one single `-pa [dir1] [dir2]` declaration, as documented here: http://erlang.org/doc/man/erl.html

**Comment by michaelklishin** [comment]
and then there are [Kubernetes-specific example repositories](https://github.com/rabbitmq/rabbitmq-clusterer#usage-in-environments-with-dynamic-hostnames-eg-kubernetes)

**Comment by michaelklishin** [comment]
Here are the effective VM flags broken down into multiple lines:

```
RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq ERL_MAX_ETS_TABLES=50000
exec erl -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/ebin -noinput
-s rabbitmq_clusterer boot -sname rabbit@5bc2e8bf26f9
-boot start_sasl -config /etc/rabbitmq/rabbitmq +W w +A 64 +P 1048576 +t 5000000
+stbt db +zdbbl 32000 +K true -kernel inet_default_connect_options [{nodelay,true}]
-pa /plugins/rabbitmq_clusterer-3.6.9.ez/rabbitmq_clusterer-3.6.x-667f92b0/ebin
-sasl errlog_type error -sasl sasl_error_logger tty -rabbit error_logger tty
-rabbit sasl_error_logger tty -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins"
-rabbit plugins_dir "/usr/lib/rabbitmq/plugins:/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/plugins"
-rabbit plugins_expand_dir "/var/lib/rabbitmq/mnesia/rabbit@5bc2e8bf26f9-plugins-expand"
-os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false
-mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@5bc2e8bf26f9" +B i
-kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
```
multple `-pa` and `-pz` arguments are certainly supported but there error is pretty unambiguous: the function given to `-s`:

```
-s rabbitmq_clusterer boot
```

is not found.

**Comment by michaelklishin** [comment]
`/plugins/rabbitmq_clusterer-3.6.9.ez` is a .zip file so its contents are easy to inspect. The idea is that non-NIF code (pure Erlang modules) can be loaded from `.ez` files if you add the `ebin` directory in such a file to VM code path.
